source 'https://github.com/CocoaPods/Specs.git'
platform :ios , 8.1
use_frameworks!

target 'BXViewPager_Example' do
  pod "BXViewPager", :path => "../"
  #pod 'Reveal-iOS-SDK',  :configurations => ['Debug']
  #pod 'PinAutoLayout'
  pod 'BXForm'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
