source 'https://github.com/CocoaPods/Specs.git'
platform :ios , 8.1
use_frameworks!

target 'BXViewPager_Example', :exclusive => true do
  pod "BXViewPager", :path => "../"
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  pod 'PinAutoLayout'
end

target 'BXViewPager_Tests', :exclusive => true do
  pod "BXViewPager", :path => "../"

  
end
